### ISSUE TITLE
Gettiing undefined method <relation> for nil:NilClass

### ISSUE THREAD

**Issue by amitsuryavanshi** [CanCanCommunity/cancancan-neo4j#2]
If you have has_one relation at start of your condition hash and you are checking access on a object that does not have that relation existing, the code gives  "undefined method <relation> for nil:NilClass" error. Stacktrace,
` NoMethodError:
       undefined method `mentions' for nil:NilClass
     Shared Example Group: "match expectations" called from ./spec/cancancan/model_adapters/neo4j_adapter_spec.rb:124
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:68:in `block in associations_conditions_match?'
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:67:in `associations_conditions_match?'
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:31:in `all_conditions_match?'
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:71:in `block in associations_conditions_match?'
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:67:in `associations_conditions_match?'
     # ./lib/cancancan/model_adapters/neo4j_adapter.rb:31:in `all_conditions_match?'
`

**Comment by amitsuryavanshi** [comment]
Resolved with https://github.com/CanCanCommunity/cancancan-neo4j/pull/3
